language: java
sudo: true
dist: trusty
install: mvn clean install -P-quality-checks -DskipTests
jdk: oraclejdk9
addons:
  apt:
    packages:
    - oracle-java9-installer

script:
- clear
notifications:
  email:
    on_success: always
    on_failure: always