language: java
sudo: true
dist: trusty
install: true
jdk: oraclejdk9
addons:
  apt:
    packages:
    - oracle-java9-installer

script:
- clear
- mvn clean install --settings test/mvnsettings.xml
notifications:
  email:
    on_success: always
    on_failure: always