language: java
sudo: true
dist: trusty
install: mvn clean install -P-quality-checks -DskipTests
jdk: oraclejdk9
addons:
  apt:
    packages:
    - oracle-java9-installer
before_install: mvn install:install-file -Dfile=src/lib/ojdbc7.jar  -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0.1 -Dpackaging=jar
script:
- clear
notifications:
  email:
    on_success: always
    on_failure: always